'use client';
import { useEffect, useRef, useState } from 'react';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from './ui';
import { parsePosition } from '@/lib/afoluku-radio/seek';
import { seconds } from '@/lib/afoluku-radio/radio';
import { exportPortrait, validateExcerpt } from '@/lib/afoluku-radio/portrait-export';
export default function PortraitExport({source,settings,onClose}){
 const [start,setStart]=useState('0:00'),[end,setEnd]=useState(seconds(Math.min(source.duration,60))),[busy,setBusy]=useState(false),[progress,setProgress]=useState(0),[error,setError]=useState(''),[result,setResult]=useState(null);
 const canvas=useRef(null),controller=useRef(null),urls=useRef([]),mounted=useRef(false),locked=useRef(false);
 useEffect(()=>{mounted.current=true;const allocated=urls.current;return()=>{mounted.current=false;controller.current?.abort();allocated.forEach(URL.revokeObjectURL);};},[]);
 async function generate(){if(locked.current)return;let from,to;try{from=parsePosition(start);to=parsePosition(end);validateExcerpt(from,to,source.duration);}catch(e){setError(e.message);return;}locked.current=true;setBusy(true);setError('');setProgress(0);setResult(null);controller.current=new AbortController();
  try{const output=await exportPortrait({source,start:from,end:to,settings,canvas:canvas.current,signal:controller.current.signal,onProgress:p=>mounted.current&&setProgress(p)});if(!mounted.current)return;const url=URL.createObjectURL(output.blob);urls.current.push(url);setResult({url,name:`AFOLUKU-RADIO-extrait-${Math.floor(from)}-${Math.floor(to)}.${output.extension}`});}catch(e){if(mounted.current)setError(e.name==='AbortError'?'Export annulé.':e.message);}finally{locked.current=false;if(mounted.current)setBusy(false);}
 }
 return <Dialog open onOpenChange={open=>{if(!open&&!busy)onClose();}}><DialogContent className="portrait-export" closeDisabled={busy}><DialogTitle>Exporter un extrait en 3:4</DialogTitle><DialogDescription>{source.title} · {seconds(source.duration)}</DialogDescription><p className="help">Vidéo avec le son, les informations du média et le logo. La préparation dure le temps de l’extrait : gardez cet onglet visible. Maximum 10 minutes par extrait.</p><div className="portrait-times"><label>Début<input aria-label="Début de l’extrait" value={start} disabled={busy} onChange={e=>{setStart(e.target.value);setResult(null);}} placeholder="01:30"/></label><label>Fin<input aria-label="Fin de l’extrait" value={end} disabled={busy} onChange={e=>{setEnd(e.target.value);setResult(null);}} placeholder="02:00"/></label></div><canvas ref={canvas} width={720} height={960} className="portrait-export-canvas" hidden={!busy}/>{busy&&<p role="status">Préparation : {Math.round(progress*100)} %</p>}{error&&<p className="notice error" role="alert">{error}</p>}{result&&<><video className="portrait-export-canvas" src={result.url} controls playsInline/><a className="primary" href={result.url} download={result.name}>Télécharger la vidéo 3:4</a></>}<div className="transport">{busy?<button className="secondary" onClick={()=>controller.current?.abort()}>Annuler l’export</button>:<button className="primary" onClick={()=>void generate()}>Préparer la vidéo</button>}<button className="secondary" disabled={busy} onClick={onClose}>Fermer</button></div></DialogContent></Dialog>;
}
