'use client';
import {Dialog as D,AlertDialog as A} from 'radix-ui';
export const SidebarProvider=({children,...p})=><div {...p}>{children}</div>;
export const Sidebar=({children,collapsible,...p})=><aside {...p}>{children}</aside>;
export const NativeSelect=({children,...p})=><select {...p} className={`field ${p.className||''}`}>{children}</select>;
export const NativeSelectOption=props=><option {...props}/>;
export const Slider=({value,onValueChange,...p})=><input {...p} type="range" className="radio-slider" value={value[0]} onChange={e=>onValueChange([Number(e.target.value)])}/>;
export const Switch=({checked,onCheckedChange,...p})=><input {...p} className="radio-switch" type="checkbox" role="switch" checked={checked} onChange={e=>onCheckedChange(e.target.checked)}/>;
export const Progress=props=><progress max="100" {...props}/>;
export const Table=props=><div className="radio-table-scroll"><table {...props}/></div>;
export const TableHeader=props=><thead {...props}/>;
export const TableBody=props=><tbody {...props}/>;
export const TableHead=props=><th {...props}/>;
export const TableCell=props=><td {...props}/>;
export const TableRow=props=><tr {...props}/>;
export const Dialog=D.Root,DialogTitle=D.Title,DialogDescription=D.Description;
export const DialogContent=({children,className,closeDisabled=false,...props})=><D.Portal><div className="afoluku-radio-app"><D.Overlay className="radio-modal-overlay"/><D.Content {...props} className={`radio-modal ${className||''}`}>{children}<D.Close disabled={closeDisabled} className="radio-modal-close" aria-label="Fermer">×</D.Close></D.Content></div></D.Portal>;
export const AlertDialog=A.Root,AlertDialogTitle=A.Title,AlertDialogDescription=A.Description;
export const AlertDialogContent=({children,...p})=><A.Portal><div className="afoluku-radio-app"><A.Overlay className="radio-modal-overlay"/><A.Content {...p} className="radio-modal">{children}</A.Content></div></A.Portal>;
export const AlertDialogFooter=props=><div {...props} className="radio-modal-actions"/>;
export const AlertDialogCancel=props=><A.Cancel {...props} className="secondary"/>;
export const AlertDialogAction=props=><A.Action {...props} className="danger"/>;
